### PR TITLE
Port changes from ShandalarImageToolbox fork

### PR DESCRIPTION
**Pull request by CelestialAmber**
I've been meaning to send a PR for a long time ever since I'd added support for other formats and completely reworked the tool from the ground up. This PR namely features:

-Support for card art images found in .cat archives (wavelet format)
-Support for .spr images
-Saving images as .png images
-Reworked/overhauled UI

Understandably you may not be okay with a lot of the changes made, but I still would like to see the main improvements make their way into the original repo. It's up to you though.

### CODE REVIEW

**Comment by ogamespec** [comment]
Whoa, that's cool :) I don't mind the changes, it was a 1-2 day project after all, glad someone could use my research :)
I don't know how to be honest... It's basically a different utility and the name PicDecoder would be too narrowly focused.

**Comment by CelestialAmber** [comment]
That's the problem about this ;^^ Maybe this could be put on a separate branch?

**Comment by ogamespec** [comment]
I can just rename the repository after the PR, I think that's the easiest thing to do. I can name it whatever you like.

**Comment by CelestialAmber** [comment]
I want to leave the choice to you.

**Comment by ogamespec** [comment]
`ShandalarToolbox` is ok?

**Comment by ogamespec** [comment]
We also need to resolve conflicts somehow, I don't know which side to do it from? :)

**Comment by ogamespec** [comment]
By the way, I don't know if you've seen these repositories or not? They are also on the topic.

https://github.com/ogamespec/WvlDecoder
https://github.com/ogamespec/CatView

**Comment by CelestialAmber** [comment]
Sorry for the late reply. ShandalarToolbox is ok by me. And yes I have seen both repos, I ported the wavelet code to C# several years ago, and borrowed some code from the .cat viewer.

**Comment by CelestialAmber** [comment]
I'll try to resolve conflicts on my end.

**Comment by CelestialAmber** [comment]
I can't seem to find a way to fix conflicts. Could you fix them on your end via a rebase or something else?

**Comment by ogamespec** [comment]
Merged & renamed :)

**Pull request merged**
